### ISSUE TITLE
Build on PYNQ (dual-core Cortex-A9) with SD v2.4 (Ubuntu 18.04)

### ISSUE THREAD

**Issue by umarcor** [DynamoRIO/dynamorio#3399]
- [Pynq](https://store.digilentinc.com/pynq-z1-python-productivity-for-zynq-7000-arm-fpga-soc/)
- [github.com/Xilinx/PYNQ/releases](https://github.com/Xilinx/PYNQ/releases)

The default GCC version is `gcc (Ubuntu/Linaro 7.3.0-16ubuntu3) 7.3.0`.

- [x] 1. `master` branch fails to build because of a bug in `opnd_shared.c`, which can be patched as explained in [#3381](https://github.com/DynamoRIO/dynamorio/issues/3381#issuecomment-467357845).
- [ ] 2. an error about `PTRACE_GETFPXREGS` is shown. It can be patched as in #3382.
- [x] 3. `undefined symbol: GLOBAL DEFAULT UND __aeabi_ldivmod` is shown. It can be patched as in [#2901](https://github.com/DynamoRIO/dynamorio/issues/2901#issuecomment-447361814) (note that the link point to a comment by @SieRoB, no to the previous one).

I'm the author of #3382, so it will be eventually merged to master and item 2 will be fixed. What about items 1 and 3? Shall I open a PR for each of them?

**Comment by derekbruening** [comment]
1 is #2900.  It would be nice to add a test for an RRX address calculation but the code fix is in.

3: Yes, please submit a fix.

**Comment by umarcor** [comment]
> 1 is #2900. It would be nice to add a test for an RRX address calculation but the code fix is in.

Can you please reopen #2900 to track the addition of a test there?

> 3: Yes, please submit a fix.

Done (#3403).

**Comment by umarcor** [comment]
Since 2/3 fixes are already merged into master, and the third one (#3382) is just pending a review, I'm closing this issue.
