### ISSUE TITLE
non-ascii strings in DR API (was "ASSERT((unsigned short)(*wstr) <= UCHAR_MAX) in our_vsnprintf")

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#943]
_From [zhao...@google.com](https://code.google.com/u/106321947286816917100/) on October 09, 2012 16:57:53_

~/Workspace/DynamoRIO/builds/build_x86_dbg.svn/bin32/drrun.exe -debug -ops "-msgbox_mask 0xf" --  ./unit_tests.exe --gtest_filter=IEImporterTest.IEImporter

int
TNAME(our_vsnprintf)(TCHAR *s, size_t max, const TCHAR *fmt, va_list ap)

```
        /* insert the actual str representation */
        if (wstr != NULL) {
            while (*wstr) {
                if (max > 0 && (size_t)(s - start) >= max)
                    goto max_reached;
                if ((*c == _T('s') || *c == _T('S')) && decimal == 0)
                    break;  /* check string precision */
                decimal--;
                /* we only support ascii */
                ASSERT((unsigned short)(*wstr) \<= UCHAR_MAX);
                *s = (TCHAR) *wstr;
                s++;
                wstr++;
            }
        } else {
```

0:000> dt wstr
Local var @ 0x17f5e8bc Type unsigned short*
0x0627c30e 
 -> 0x4e2d

_Original issue: http://code.google.com/p/dynamorio/issues/detail?id=943_

<hr>

Breakdown of sub-tasks:
- [X] Implement UTF-8 to UTF-16 and vice versa conversion routines in the core
- [X] Use UTF-8<->UTF-16 in our_vsnprintf %S
- [X] Document in main docs and dr_sn{w,}printf headers
- [X] drsyms: switch SymLoadModule to SymLoadModuleExW
- [X] drsyms (#1085): use SymGetLineFromAddrW64
- [X] drdeploy (i#1079): GetEnvironmentVariableA, _access(), main(), etc. 
- [X] drdeploy: use _tfopen()
- [X] drdeploy: _tmain
- [X] drconfiglib: GetEnvironmentVariableA, CreateDirectoryA, convert_to_tchar() needs to use MultiByteToWideChar() + need to ensure all sources are UTF-8
    (for env var can just use drfront_get_env_var() nowadays)
- [X] drinjectlib: API
- [ ] injection: LoadLibraryA
- [X] drconfiglib: TSTR_FMT snprintf needs to use our_snprintf or char_to_tchar
- [ ] tolower() and its callers (strcasecmp(), strcasecmp_with_wildcards(), str_case_prefix())
- [ ] drcontainers hashtable case-insensitive hashing
- [ ] DrMem tolower() calls in text_matches_pattern() + strcasestr()
- [ ] drcov2lcov FindFirstFile

**Comment by derekbruening** [comment]
** TODO DrMem has tolower() calls

We should replace tolower() calls in text_matches_pattern() and
strcasestr() with the same soln we use for DR: ideally our own
locale-independent case folding.

**Comment by derekbruening** [comment]
In commit 46cbef71027af7e3a279321560a7b0f876e25833

    i#943 non-ascii: non-ascii username and non-ascii app path support
    
    Fixes the drinjectlib API to handle non-ascii application path and
    arguments.
    
    Fixes drdeploy's tool file and other (non-config) file manipulation to
    handle non-ascii paths.
    
    Fixes drdeploy.c to use _tmain and handle non-ascii parameters.
    
    Fixes drconfiglib's GetEnvironmentVariableA, SetEnvironmentVariableA,
    CreateDirectoryA, convert_to_tchar, and fopen to handle non-ascii strings.
    
    This means that non-ascii usernames and non-ascii app paths now work.
    However, a non-ascii DynamoRIO path will not yet work.

For the remaining work (we also have the tolower and hashtable case issues too):

*** TODO TSTR_FMT needs to be removed and all uses replaced, or use our_snprintf

dr_config.c is using Windows _snprintf with %S/%ls to convert to/from
utf16, which is broken and does not work.

We either need to have it use io.c (requires refactoring to let io.c pull
in just types from globals.h w/o other stuff; maybe make a static lib for
it), or do explicit conversion everywhere.

*** TODO injection is calling LoadLibraryA with a utf8 path

Thread injection will be loading a utf8 dll path read
from the config file and passing it to LoadLibraryA.

Can we afford to call our conversion at inject time?  If we switch to
storing utf16 in the config file we'll have to change a lot of code that's
passing char*.

**Comment by derekbruening** [comment]
The TSTR_FMT uses in dr_config.c were fixed in 639b429

A bug in full_path of the exe was fixed in af45400

Thus a non-ascii username, non-ascii app path, and non-ascii client options (like DrM logdir) all work now.

The biggest thing that does not work is a non-ascii DR path.  Other minor things remaining are the tolower calls in DR, drcontainers, and DrM.

**Comment by derekbruening** [comment]
drcov2lcov does not handle non-ascii as it uses FindFirstFileA.
